import Image from 'next/image'
import React from 'react'
import nextjs11 from "../../../../public/nextjs11.jpg"
import { MdAccountCircle } from "react-icons/md";
const page = () => {
  return (
    <div className='mt-[50px] mb-[100px]'>
        <div className='lg:w-[800px] px-9 lg:px-12 lg:ml-72'>
        <h1 className="text-3xl lg:mb-[50px] font-extrabold text-center text-myverydarkpink dark:text-white md:text-4xl lg:text-5xl text-transparent bg-clip-text bg-gradient-to-r to-gray-700 from-black ">NextJs v11.0.0</h1>
        <h1 className='flex mt-2 lg: mb-4'><a href="https://github.com/Ghaniya08"><MdAccountCircle className='text-3xl mr-3' /></a> Ghaniya Khan <span className='ml-4'> November 2 2024</span></h1>
        <Image src={nextjs11} alt='next2' className='rounded-lg lg:h-[350px] lg:w-[110250px] w-[300px]'/>
      <p  className='lg:leading-7 lg:text-[16px] text-[12px] lg:[&:not(:first-child)]:mt-6 mb-3'>Next.js has become a go-to framework for developers building fast, scalable, and SEO-friendly React applications. With each update, Next.js enhances its capabilities, offering powerful features that simplify both development and deployment. Next.js v11, released by Vercel, introduced a series of new improvements and updates that focus on enhancing developer experience, improving collaboration, and making applications faster and more user-friendly.</p>
      <p className='lg:leading-7 lg:text-[16px] text-[12px] lg:[&:not(:first-child)]:mt-6 mb-3'>In this post, we’ll explore the key features of Next.js v11, understand why its an important update, and look at how it can benefit developers and businesses alike.</p>
      <h1 className="scroll-m-20 border-b lg:pb-2 lg:text-2xl text-xl font-semibold tracking-tight first:mt-0">Key Features in Next.js v11</h1>
      <p className='lg:leading-7 lg:text-[16px] text-[12px] lg:[&:not(:first-child)]:mt-6 mb-3'> <span className="scroll-m-20 border-b pb-2 text-[17px] font-semibold tracking-tight first:mt-0">Next.js Live: Real-Time Collaboration: </span>One of the most groundbreaking features introduced in Next.js v11 is Next.js Live. This feature enables developers to collaborate in real-time directly in the browser. Next.js Live removes the need for local development environments, making it possible for teams to share a link and work together seamlessly on code changes, debugging, and testing. This feature is especially useful for remote teams, as it allows everyone to stay on the same page without needing complex setup processes.</p>
      <p className='lg:leading-7 lg:text-[16px] text-[12px] lg:[&:not(:first-child)]:mt-6 mb-3'> <span className="scroll-m-20 border-b pb-2 text-[17px] font-semibold tracking-tight first:mt-0"> Automatic Image Optimization Improvements: </span>Image optimization has been one of Next.js’s standout features, and in v11, it’s even better. With automatic support for AVIF format (a next-gen image format that offers excellent quality and smaller file sizes), images load faster, improving the Core Web Vitals metrics. This update is key for applications that prioritize speed and performance since optimized images can significantly reduce page load times and boost user engagement.</p>
      <p className='lg:leading-7 lg:text-[16px] text-[12px] lg:[&:not(:first-child)]:mt-6 mb-3' > <span className="scroll-m-20 border-b pb-2 text-[17px] font-semibold tracking-tight first:mt-0">Conformance: Coding Standards Enforcement:  </span>Next.js v11 introduces a new feature called Conformance, which helps developers adhere to best practices. It identifies potential issues in code and alerts developers in real time. This helps enforce coding standards and prevents problems like oversized bundles or non-performant code from slipping through. Conformance is a proactive approach to maintain code quality and improve performance without needing extra plugins or manual checks.</p>
      <p className='lg:leading-7 lg:text-[16px] text-[12px] lg:[&:not(:first-child)]:mt-6 mb-3'> <span className="scroll-m-20 border-b pb-2 text-[17px] font-semibold tracking-tight first:mt-0">Improved Developer Experience with ESLint Integration: </span>Next.js v11 includes built-in ESLint support, allowing developers to detect and fix issues as they code. ESLint is essential for identifying bugs, enforcing code style, and keeping code clean. By integrating ESLint directly into Next.js, developers save time setting up linting and get immediate feedback on potential issues, streamlining the development process.</p>
      <p className='lg:leading-7 lg:text-[16px] text-[12px] lg:[&:not(:first-child)]:mt-6 mb-3'> <span className="scroll-m-20 border-b pb-2 text-[17px] font-semibold tracking-tight first:mt-0">Faster Refresh and Start-Up Times: </span>Speed improvements in Next.js v11 enhance hot-reloading times and reduce the time it takes for the development server to start. This update leads to a smoother development workflow, allowing developers to iterate quickly and efficiently without waiting for changes to load. This is especially helpful for large-scale projects where faster reload times save significant development time.</p>
      <h1 className="scroll-m-20 border-b lg:pb-2 lg:text-2xl text-xl font-semibold tracking-tight first:mt-0">Why Upgrade to Next.js v11? </h1>
      <p className='lg:leading-7 lg:text-[16px] text-[12px] lg:[&:not(:first-child)]:mt-6 mb-3'>Next.js v11 brings a collection of enhancements that streamline development, improve collaboration, and boost application performance. By upgrading to Next.js v11.</p> 
        </div>
    </div>
  )
}

export default page
